---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-event-exporter
  namespace: k8s-event-exporter
  labels:
    app: k8s-event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-event-exporter
  template:
    metadata:
      labels:
        app: k8s-event-exporter
    spec:
      serviceAccountName: k8s-event-exporter
      containers:
        - name: k8s-event-exporter
          image: gcr.io/namespace/k8s-event-exporter
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: k8s-event-exporter
  namespace: k8s-event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-event-exporter
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    resourceNames: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-event-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-event-exporter
    namespace: k8s-event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-event-exporter
---
kind: Namespace
apiVersion: v1
metadata:
  name: k8s-event-exporter