---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-event-exporter
  namespace: k8s-event-exporter
  labels:
    app: k8s-event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-event-exporter
  template:
    metadata:
      labels:
        app: k8s-event-exporter
    spec:
      initContainers:
        - name: create-mongodb-indexes
          image: pydo/k8s-event-exporter:latest
          imagePullPolicy: Always
          command: ["python"]
          args: ["src/database/db.py"]
          env:
            - name: MONGO_HOST
              value: mongodb.default.svc.cluster.local
          envFrom:
            - secretRef:
                name: mongodb-credentials
      serviceAccountName: k8s-event-exporter
      containers:
        - name: k8s-event-exporter
          image: pydo/k8s-event-exporter:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_HOST
              value: mongodb.default.svc.cluster.local
          envFrom:
            - secretRef:
                name: mongodb-credentials
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: k8s-event-exporter
  namespace: k8s-event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-event-exporter
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    resourceNames: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-event-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-event-exporter
    namespace: k8s-event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: Namespace
apiVersion: v1
metadata:
  name: k8s-event-exporter